---
- name: Check if xmllint is installed
  package_facts:
    manager: auto

- name: Install libxml2-utils Alpine
  apk:
    name: libxml2-utils
    state: latest
  when: "'libxml2-utils' not in ansible_facts.packages and ansible_os_family == 'Alpine'"

- name: Enable EPEL Repository on CentOS 8
  yum:
    name: epel-release
    state: latest
  when: "'libxml2' not in ansible_facts.packages and ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '8'"

- name: Install libxml2 on RedHat
  yum:
    name: libxml2
    state: latest
  when: "'libxml2' not in ansible_facts.packages and ansible_os_family == 'RedHat'"

- name: Populate XML file
  template:
    src: "{{ templates_folder }}/{{ item }}"
    dest: "{{ item }}-{{ env }}"
  with_items:
    - "{{ xml_file }}"

- name: Populate XSD file
  template:
    src: "{{ templates_folder }}/{{ item }}"
    dest: "{{ item }}-{{ env }}"
  with_items:
    - "{{ xsd_file }}"

- name: "Validation with xmllint"
  shell: "xmllint --schema {{ item.0 }}-{{ env}} {{ item.1 }}-{{ env}}"
  with_together:
    - "{{ xsd_file }}"
    - "{{ xml_file }}"