---
- name: Check if xmllint is installed
  package_facts:
    manager: auto

- name: Install libxml2-utils Alpine
  apk:
    name: libxml2-utils
    state: latest
  when: "'libxml2-utils' not in ansible_facts.packages and ansible_os_family == 'Alpine'"

- name: Enable EPEL Repository on CentOS 8
  yum:
    name: epel-release
    state: latest
  when: "'libxml2' not in ansible_facts.packages and ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '8'"

- name: Install libxml2 on RedHat
  yum:
    name: libxml2
    state: latest
  when: "'libxml2' not in ansible_facts.packages and ansible_os_family == 'RedHat'"

- name: Populate XML file
  template:
    src: "{{ xml_templates_folder }}/{{ item }}"
    dest: "{{ item }}-{{ env }}"
    mode: u=rwx,g=rwx,o=rx,g+s
  with_items:
    - "{{ xml_file }}"

- name: Populate XSD file
  template:
    src: "{{ xsd_templates_folder }}/{{ item }}"
    dest: "{{ item }}-{{ env }}"
    mode: u=rwx,g=rwx,o=rx,g+s
  with_items:
    - "{{ xsd_file }}"

- name: "Validation with xmllint"
  ansible.builtin.command: "xmllint --schema {{ item.0 }}-{{ env}} {{ item.1 }}-{{ env}}"
  register: xmlvallidation 
  changed_when: xmlvallidation.rc != 0
  with_together:
    - "{{ xsd_file }}"
    - "{{ xml_file }}"

- name: Delete validated files
  file:
    path: "{{ item }}-{{ env }}" #correction code
    state: absent
  with_items:
    - "{{ xsd_file }}"
    - "{{ xml_file }}"